### ISSUE TITLE
GFPAdManagerDelegate 구현 관련 문의

### ISSUE THREAD

**Issue by hm138** [naver/nam-sdk-ios#10]
아래 내용 문의드립니다.
1. GFPAdManagerDelegate 구현하지 않았을 경우 제약사항
2. GFPAdManagerDelegate 필수적으로 구현되어야하는지 여부

**Comment by shhan-sys** [comment]
@hm138 님, 안녕하세요
해당 사항 답변 드리겠습니다.

1. 구현하지 않았을 경우 권한 획득 문제로 차후 FAN 지면 적용 등 제대로 동작하지 않을 가능성이 있습니다.
- 실제로 sdk에서 권한을 요청하지는 않고, 서비스 측에서 사용하는 경우에만 사용합니다.

2. 필수적 구현 사항으로 안내하고 있습니다. 
- 다만, ATT Framework를 현재 사용하고 있지 않으시다면, 기본값인 GFPATTAuthorizeNotDetermined 를 리턴하도록 구현해주시고, 추후에 서비스에서 ATT Framework를 사용하실 때에 맞춰서 구현만 변경해주시면 됩니다.

**Comment by hm138** [comment]
넵. 확인하였습니다.
지원해주셔서 감사합니다.
