### ISSUE TITLE
통계 확인 요청

### ISSUE THREAD

**Issue by hyungyoung123** [naver/nam-sdk-ios#11]
Syrup iOS QA 측면에서 하기 사항에 대해 확인을 부탁합니다.
 
-       IDFA : 4D674F1E-8607-44C7-B3F8-B4F40DBBFBB7
-       테스트 시간 : 8월12일 08:00 ~ 09:00
-       확인 요청 사항 : 하기 "광고유닛ID"위치에서의 Ad Req(요청수) &  Imp Counting
       o SYRUP_IOS_NATIVE_MYTAP1-N120585387
       o SYRUP_IOS_BANNER_YAKUM1-N120585387
       o SYRUP_IOS_BANNER_YAKUM2-N120585387

**Comment by NAM-Ad** [comment]
@hyungyoung123 님, 

문의주신 adid 기준으로 저희 쪽에서 확인되는 로그는 없는 상황입니다. 

/cc @hm138

----

**<요약>**

Syrup iOS 지면의 경우, 아래와 같이 adid가 정상적으로 전달되지 않아 광고 선출이 발생하지 않고 있습니다. 
- `MYTAP, YAKUM1`  : adid는 전달하고 있으나 잘못된 값이라 수정이 필요합니다. [ojbect Object]라는 값으로 전달 중입니다.
- `YAKUM 2` : AOS와 동일하게 adid가 전달되지 않고 있습니다.  


지면 | adUnitId | adid | 비고
-- | -- | -- | --
마이탭 | SYRUP_IOS_NATIVE_MYTAP1-N120585387 | 잘못전달 | [object Object]라는 값으로   전달 중
야금야금>모으기 | SYRUP_IOS_BANNER_YAKUM1-N120585387 | 잘못전달 | [object Object]라는 값으로   전달 중
야금야금>출첵 | SYRUP_IOS_BANNER_YAKUM2-N120585387 | 미전달 |

**Comment by hyungyoung123** [comment]
@NAM-Ad님,
Syrup > iOS > 마이탭 & 야금 모으기 adUnitId에 IDFA 조치가 완료되었고,
광고 노출도 정상적으로 되고 있음을 확인하였습니다.

"야금 출첵"은 조치가 완료되는 대로 다시 공유드리겠습니다.

**Comment by NAM-Ad** [comment]
@hyungyoung123 
금일 SKP 측 상용 배포 후, 현재 Syrup iOS 전 지면에서 adid 정상적으로 전달되고 있는 것으로 확인됩니다.
> 문제가 됐던 Syrup AOS `SYRUP_AOS_BANNER_YAKUM2-N120585387` 유닛도 해결되었습니다. 

광고 노출까지 이슈없는 것으로 확인됩니다. 
저희 쪽에서 추가로 확인 필요한 내용 있으면 말씀 주십시오. 

지면 | adUnitId | adid 전달여부
-- | -- | -- 
마이탭 | SYRUP_IOS_NATIVE_MYTAP1-N120585387 | 전달
야금야금>모으기 | SYRUP_IOS_BANNER_YAKUM1-N120585387 | 전달
야금야금>출첵 | SYRUP_IOS_BANNER_YAKUM2-N120585387 | 전달
