### ISSUE TITLE
GFPAdLoaderDelegate 에러 확인 요청

### ISSUE THREAD

**Issue by leejj121** [naver/nam-sdk-ios#12]
adLoader loadAd() 관련애서 아래 에러에 대한 처리 방안 확인 요청 드립니다. 

[16:52:17.7190][HomeViewController-adLoader(_:didFailWithError:responseInfo:):1487] - error : Optional([GFPError Code=3310 CodeName=GFPErrorNoFill UserInfo={"gfpsdk.error.message" = "There are currently no valid ads.";
}])

그리고 가이드 문서만 확인했는데요. 
추가적으로 api 에 대한 세부 문서도 있을까요?

**Comment by shhan-sys** [comment]
안녕하세요, @leejj121 님. 3310 - There are currently no valid ads. 해당 에러는 현재 서빙되어 보여질 광고가 없는 상황에 발생합니다. 광고가 잘 나오다가 안나오시는 경우일까요, 아니면 아예 처음부터 나오지 않으신 경우일까요?

가이드 문서 외에 별도 api 세부 문서는 존재하지 않습니다.

**Comment by leejj121** [comment]
안녕하세요. 현재 sdk 를 적용중이어서 처음 나온 에러입니다. 아직 광고 노출은 확인하지 못하였습니다.

**Comment by shhan-sys** [comment]
테스트 중이신 유닛 id가 어떻게 되실까요?

**Comment by shhan-sys** [comment]
현재 저장소에 첨부된 Swift Sample 에서는 해당 내용으로 출력이 잘 되고 있습니다.
![image](https://user-images.githubusercontent.com/73639746/217193035-d0a245a2-0702-43fe-9007-a3c9a713e486.png)

podfile이나 광고 호출 시 sdk 초기화 여부 상태를 알 수 있을까요?

**Comment by leejj121** [comment]
아래처럼 처리 되어 있습니다. 

#. podfile 

pod 'NAMSDK/MediationNDA'

#. 초기화 관련
GFPAdManager.setup(withPublisherCd: publisher, target: self, configuration: configuration) { error in
            Log("error : \(error)")
        }
-> 결과값 "error : nil"

**Comment by shhan-sys** [comment]
확인 감사합니다. 
혹시 광고 호출 시점에 GFPAdManager.isSdkInitialized 로 loadAd() 호출 전에 확인하고 있을까요?

**Comment by leejj121** [comment]
관련 호출에 따른 로그 전달 드립니다. 


[18:02:28.8320][AppDelegate-initializeNamSDK():103] - NAMSDK error : nil
[18:02:31.3970][HomeViewController-requestNamAD():163] - NAMSDK GFPAdManager.isSdkInitialized() : true
[18:02:32.1540][HomeViewController-adLoader(_:didFailWithError:responseInfo:):1492] - NAMSDK error : Optional([GFPError Code=3310 CodeName=GFPErrorNoFill UserInfo={"gfpsdk.error.message" = "There are currently no valid ads.";

광고 요청은 아래 코드록 하고 있습니다. 

        let adParam = GFPAdParam()
        adParam.yearOfBirth = 1990
        adParam.gender = .male
            
        let unitID = "Tmap_AdUnit_main_ios-N774476171"
        self.adLoader = GFPAdLoader(unitID: unitID, rootViewController: self, adParam: adParam)
            
        let bannerOption = GFPAdBannerOptions()
        bannerOption.layoutType = .fluidWidth
        bannerOption.hostMeta = ["light":"theme"]
        self.adLoader?.setBannerDelegate(self, bannerOptions: bannerOption)

        self.adLoader?.delegate = self
        self.adLoader?.loadAd()

**Comment by shhan-sys** [comment]
@leejj121 님, 마지막으로 죄송하지만 초기화 시에 사용하는 publisherCode 알려주실 수 있으실까요?

**Comment by leejj121** [comment]
초기화 코드는 아래처럼 하고 있습니다. 

let configuration = GFPAdConfiguration()
        configuration.logLevel = .info
        let publisher = "N774476171"
        GFPAdManager.setup(withPublisherCd: publisher, target: self, configuration: configuration) { error in
            Log("NAMSDK error : \(error)")
        }

**Comment by shhan-sys** [comment]
@leejj121 님, 해당 유닛 아이디는 네이티브 광고를 응답으로 받고 있습니다.
광고 로드 부분을 해당 부분으로 바꿔서 테스트 부탁드리겠습니다~
```
        let adParam = GFPAdParam()
        adParam.yearOfBirth = 1990
        adParam.gender = .male

        let unitID = "Tmap_AdUnit_main_ios-N774476171"
        self.adLoader = GFPAdLoader(unitID: unitID, rootViewController: self, adParam: adParam)
        let nativeSimpleOption = GFPAdNativeSimpleOptions()

        let simpleRenderingSetting = GFPNativeSimpleAdRenderingSetting()
        nativeSimpleOption.simpleAdRenderingSetting = simpleRenderingSetting

        self.adLoader?.setNativeSimpleDelegate(self, nativeSimpleOptions: nativeSimpleOption)


        self.adLoader?.delegate = self
        self.adLoader?.loadAd()
```

**Comment by leejj121** [comment]
위 내용으로 에러 없이 동작은 확인했습니다. 
추가적으로 View 에 대한 연결은 xib 에 대해서만 지원하나요?
코드로 화면 구성하는 형태에서의 처리는 어떻게 하면 될까요?

**Comment by shhan-sys** [comment]
@leejj121 님, 해당 코드 참조해주시면 될 듯 합니다.
```
// GFPAdLoaderDelegate method

func adLoader(_ unifiedAdLoader: GFPAdLoader, didReceive nativeSimpleAd: GFPNativeSimpleAd) {
    let mediaView = GFPMediaView()
    mediaView.frame  = adView.frame
    mediaView.autoresizingMask = [.flexibleWidth, .flexibleHeight]

    let nativeSimpleAdView = GFPNativeSimpleAdView()
    nativeSimpleAdView.addSubView(mediaView)
    nativeSimpleAdView.mediaView = mediaView
    nativeSimpleAdView.nativeAd = nativeSimpleAd
    nativeSimpleAdView.frame = adView.frame
    nativeSimpleAdView.autoresizingMask = [.flexibleWidth, .flexibleHeight]

    adView.adSubview(nativeSimpleAdView)
 
    ...


}
```

**Comment by leejj121** [comment]
위 코드로 표출 확인하였습니다 

추가로 문의사항있는데요.
광고 요청시, 아래 설정하는 GFPNativeSimpleAdDelegate delegate 와 
- self.adLoader?.setNativeSimpleDelegate(self, nativeSimpleOptions: nativeSimpleOption)

adLoader 이벤트 함수에서 넘어온 simpleAd의 delegate가 같은 형식인데, 
- func adLoader(_ unifiedAdLoader: GFPAdLoader!, didReceive simpleAd: GFPNativeSimpleAd!) {

동일하게 Simple AD 관련 이벤트를 처리하는것인가요? 
그럼,, 위 2개중 하나에서만 delegate 가 설정되면 이벤트는 정상 수신되는건가요?

**Comment by shhan-sys** [comment]
GFPAdLoaderDelegate는 광고 로드 및 실패에 관한 GFPAdLoader에 관련된 delegate이구요,
GFPNativeSimpleAdDelegate 는 광고가 로드된 이후에 native simple ad 에 대해서 작동하는 delegate입니다.

**Comment by leejj121** [comment]
네. GFPAdLoaderDelegate 는 adLoader 대한 이벤트인거 확인했습니다. 
GFPNativeSimpleAdDelegate 델리게이트가 가이드에 2번 설정되는데, 같은 동작을 하는 delegate 인가요? 


#. GFPAdLoader.h 파일
/**
 * 통합 로더를 통해 네이티브 이미지형 (Native Simple) 로드 시 사용.
 * @param nativeSimpleDelegate 광고 요청 결과를 받을 수 있는 delegate.
 * @param nativeSimpleOptions   네이티브 광고 옵션 설정 (SimpleAdRenderingSetting - Default : YES)
*/
- (void)setNativeSimpleDelegate:(id <GFPNativeSimpleAdDelegate>)nativeSimpleDelegate
            nativeSimpleOptions:(nullable GFPAdNativeSimpleOptions *)nativeSimpleOptions;


#. GFPNativeAd.h 파일
@interface GFPNativeSimpleAd : GFPNativeAdBase
@property(readwrite, nonatomic, weak) id <GFPNativeSimpleAdDelegate> delegate;




그리고, 아래 광고 요청 동작에서,, 

1. SDK initialize
2. ADLoader load
3. GFPNativeSimpleAdView.nativeAd 설정

1번은 sdk 초기화, 2번은 network time, 3번은 view rendering time 정도가 소요된다고 이해하면 될까요?

**Comment by shhan-sys** [comment]
넵, 1,2,3번 말씀하신대로 이해하시면 됩니다. 

NativeSimpleOption 설정할 때 전달하는 delegate를 GFPAdLoader 내부에서 simple 광고가 완료될 때 set 해서 완료 콜백을 보내줍니다.
같은 동작을 하는 delegate로 유동적으로 사용해주시면 될 듯 합니다.
