### ISSUE TITLE
광고 우 상단의 "AD | X" 영역 설정 관련 문의

### ISSUE THREAD

**Issue by leejj121** [naver/nam-sdk-ios#13]
앱 화면에서 아래와 같이 광고를 추가 하였는데요. 이미지 광고 옆쪽으로 여백이 있음에도 "AD | X"  버튼 영역이 노출되고 있습니다. 
이와 관련해 위치 조정을 할수 있는 API 가 있을까요?

![Screenshot 2023-02-14 at 3 57 30 PM](https://user-images.githubusercontent.com/8611217/218662228-64e57e3a-8db5-4ca0-9813-af0c344e903b.png)

**Comment by shhan-sys** [comment]
안녕하세요, 해당 애드마크 및 adchoice는 sdk 내부에서 자체 스펙으로 그리는 부분으로 변경되는 api는 제공되지 않고 있습니다.

**Comment by leejj121** [comment]
네. 확인 감사합니다.
