### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException 확인 요청

### ISSUE THREAD

**Issue by leejj121** [naver/nam-sdk-ios#17]
안녕하세요. 
Tmap 에서 메인 화면에서 광고를 띄우고 있는데, 아래 Crash가 발생하고 있어서 확인 요청 드립니다. 
추가로 필요한 사항이 있으면 말씀해주세요.

이용버전은 아래와 같습니다. 
  - NAMSDK/GFPSDK (4.5.3):
    - KissXML (~> 5.2)
  - NAMSDK/MediationNDA (4.5.3):
    - NAMSDK/GFPSDK

Fatal Exception: NSInternalInconsistencyException
Collection view delegate returned a negative size {-13.5, 26.25} from -collectionView:layout:sizeForItemAtIndexPath: for item 0 in section 0, which is not supported by flow layout. Delegate: <GFPNDAAdMuteReasonView: 0x12e807330; frame = (0 0; 32 70); hidden = YES; autoresize = W+H; backgroundColor = UIExtendedSRGBColorSpace 0.960784 0.968627 0.992157 1; layer = <CALayer: 0x28080a2e0>>; collection view: <GFPNDAReasonCollectionView: 0x10b98f800; baseClass = UICollectionView; frame = (15 33.9375; 2 26.25); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2806a8150>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x280907520>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x12e808420>; dataSource: <GFPNDAAdMuteReasonView: 0x12e807330; frame = (0 0; 32 70); hidden = YES; autoresize = W+H; backgroundColor = UIExtendedSRGBColorSpace 0.960784 0.968627 0.992157 1; layer = <CALayer: 0x28080a2e0>>>

# Crashlytics - Stack trace
# Application: com.SKTelecom.TMap
# Platform: apple
# Version: 9.20.0 (113)
# Issue: 92af8ec70bafd65886bb8ccff828e78f
# Session: 3aec8609b4d64274b3e17667c9982beb_DNE_0_v2
# Date: Fri Jun 16 2023 13:13:18 GMT+0900 (Korean Standard Time)

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9cb4 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  Foundation                     0x4e156c _userInfoForFileAndLine
3  UIKitCore                      0x62030 -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:]
4  UIKitCore                      0x6191c -[UICollectionViewFlowLayout _fetchItemsInfoForRect:]
5  UIKitCore                      0x75d80 -[UICollectionViewFlowLayout prepareLayout]
6  UIKitCore                      0x74044 -[UICollectionViewData _prepareToLoadData]
7  UIKitCore                      0x43d12c -[UICollectionViewData validateLayoutInRect:]
8  UIKitCore                      0x28f4c -[UICollectionView layoutSubviews]
9  UIKitCore                      0x4be0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
10 QuartzCore                     0xa074 CA::Layer::layout_if_needed(CA::Transaction*)
11 UIKitCore                      0xcf2c0 -[UIView(Hierarchy) layoutBelowIfNeeded]
12 UIKitCore                      0x344f38 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
13 UIKitCore                      0x344e10 -[_UIViewControllerTransitionContext __runAlongsideAnimations]
14 UIKitCore                      0x4e9690 -[_UIWindowAnimationController animateTransition:]
15 UIKitCore                      0x28e844 -[UIWindow _adjustSizeClassesAndResizeWindowToFrame:]
16 UIKitCore                      0x28cb90 -[UIWindow _resizeWindowFrameToSceneBoundsIfNecessary]
17 UIKitCore                      0x34ea34 __78-[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:]_block_invoke
18 UIKitCore                      0xdca5c __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2
19 UIKitCore                      0x2191bc +[UIView _performBlockDelayingTriggeringResponderEvents:forScene:]
20 UIKitCore                      0x3abad4 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke
21 UIKitCore                      0x2c9d24 -[_UIWindowRotationAnimationController animateTransition:]
22 UIKitCore                      0x2c9ab0 -[UIWindow _rotateToBounds:withAnimator:transitionContext:]
23 UIKitCore                      0x2c9750 -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:]
24 UIKitCore                      0x2c8a14 -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:]
25 UIKitCore                      0xd7163c -[UIWindow _internal_setRotatableViewOrientation:updateStatusBar:duration:force:]
26 UIKitCore                      0xd71a24 -[UIWindow cancelOrientationTransaction:]
27 UIKitCore                      0xaf1c54 -[_UIForcedOrientationTransactionToken cancel]
28 UIKitCore                      0x7677d4 -[_UIFullscreenPresentationController _transitionDidEnd:isDismissal:]
29 UIKitCore                      0x27a26c -[_UIFullscreenPresentationController presentationTransitionDidEnd:]
30 UIKitCore                      0x765824 __80-[UIPresentationController _initViewHierarchyForPresentationSuperview:inWindow:]_block_invoke_7
31 UIKitCore                      0x278624 -[UIPresentationController transitionDidFinish:]
32 UIKitCore                      0x14debc -[_UICurrentContextPresentationController transitionDidFinish:]
33 UIKitCore                      0x7650fc __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.110
34 UIKitCore                      0x2b24a0 -[_UIViewControllerTransitionContext completeTransition:]
35 T map                          0xb737a4 thunk for @escaping @callee_guaranteed (@unowned Bool) -> () (<compiler-generated>)
36 UIKitCore                      0x1060830 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__
37 UIKitCore                      0xce8d8 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
38 UIKitCore                      0xcd834 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
39 UIKitCore                      0xccf50 -[UIViewAnimationState animationDidStop:finished:]
40 UIKitCore                      0xcd064 -[UIViewAnimationState animationDidStop:finished:]
41 QuartzCore                     0x13624 CA::Layer::run_animation_callbacks(void*)
42 libdispatch.dylib              0x3eac _dispatch_client_callout
43 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain
44 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF
45 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
46 CoreFoundation                 0x7a560 __CFRunLoopRun
47 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific
48 GraphicsServices               0x135c GSEventRunModal
49 UIKitCore                      0x39d6e8 -[UIApplication _run]
50 UIKitCore                      0x39d34c UIApplicationMain
51 T map                          0xc5ef0 main + 11 (main.swift:11)
52 ???                            0x1a67f2dec (Missing)

아래 내용은 구동중에 나오는 assert 로, 함께 공유 드립니다. 

2023-06-16 13:56:16.453049+0900 T map[7650:1212822] [Assert] Negative or zero item sizes are not supported by flow layout. Make a symbolic breakpoint at UICollectionViewFlowLayoutAlertForInvalidItemSize to catch this in the debugger. Invalid size: {-29.5, 0}; collection view: (null)

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요
해당 이슈 관련된 부분 방어코드 추가된 버전 4.5.4가 배포되었습니다.
해당 버전으로 적용 부탁드리겠습니다~

**Comment by leejj121** [comment]
수정 확인하였습니다. 
감사합니다.
