### ISSUE TITLE
Crash 이슈 확인 요청

### ISSUE THREAD

**Issue by leejj121** [naver/nam-sdk-ios#20]
안녕하세요. 
Tmap 에서 crash 이슈가 있어서 관련 정보 전달 드립니다. 
추가로 필요한 사항이 있으면 말씀해주세요. 확인 부탁드립니다. 

#. Pod
  - NAMSDK/GFPSDK (4.5.4):
    - KissXML (~> 5.2)
  - NAMSDK/MediationNDA (4.5.4):
    - NAMSDK/GFPSDK

#. call stack
Crashed: com.apple.NSURLSession-delegate
0  libobjc.A.dylib                0x3554 objc_release_x0 + 16
1  libobjc.A.dylib                0x3554 objc_release + 16
2  T map                          0x10076ac __37-[GFPNDAFeedbackLoader loadDataWith:]_block_invoke + 4354078380
3  CFNetwork                      0x208d4 CFURLRequestSetMainDocumentURL + 2972
4  CFNetwork                      0x30958 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 13720
5  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
7  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
8  libdispatch.dylib              0xc214 _dispatch_lane_invoke + 436
9  libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
10 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
11 libsystem_pthread.dylib        0xb98 start_wqthread + 8

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요
해당 이슈는 AdMute 쪽 이슈인 듯 보이는데요,
최신 버전인 6.3.0으로 업데이트 이후 발생하는 지 확인 부탁드려도 될까요?

- 마이그레이션 참조 가이드
https://naver.github.io/nam-sdk-guide/ios/common/migration_to_5
https://naver.github.io/nam-sdk-guide/ios/common/migration_to_6

**Comment by leejj121** [comment]
네. 최신버전에서 다시 확인해 보도록하겠습니다. 
감사합니다.

**Comment by leejj121** [comment]
안녕하세요. 
해당 crash 가 6.1.2 에서도 동일하게 나타나는데요.
6.3.0 은 정식 릴리즈가 안된것 같은데, 6.3.0으로 사용해도 될까요? 
관련해서 6.3.0 릴리즈 노트도 따로 있을까요?

https://naver.github.io/nam-sdk-guide/ios/common/release_note

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요.
금주 중 6.4.5가 배포될 예정인데요, 
해당 버전으로 사용을 부탁드리겠습니다.
배포 이후에 해당 이슈를 통해 멘션 드리겠습니다.

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요.
오늘 6.5.0이 배포되었습니다.
해당 버전으로 적용 부탁드리겠습니다~

**Comment by leejj121** [comment]
@shhan-sys 님, 문의 사항이 있는데,
아래 api 에서 rootViewController 를 참조하는 이유가 있을까요? 
그리고 rootViewController가 releae 되면 이슈가 있을까요?

/**
 * 통합 로더 초기화.
 * @param adUnitID              배너 광고 유닛 아이디
 * @param rootViewController    루트 뷰 컨트롤러
 * @param adParam               광고 요청에 사용할 파라미터
 */
- (instancetype)initWithUnitID:(NSString *)adUnitID
            rootViewController:(UIViewController *)rootViewController
                       adParam:(GFPAdParam *)adParam;

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요.
SKAdNetwork 등 내부적으로 rootViewController가 필요한 경우가 있어 전달받고 있습니다.
weak ref로 참조하고 있어 release 되더라도 문제는 없습니다.
