### ISSUE TITLE
v6.1.2  AutoreleasePoolPage crash 관련 확인 요청

### ISSUE THREAD

**Issue by leejj121** [naver/nam-sdk-ios#21]
안녕하세요.
Tmap 에서 이번에 Naver AD Version 6.1.2 를 새로 올려서 사용하고 있는데요.
App 구동시, 초기에 아래 형태의 crash 가 현재 많이 올라오고 있습니다. 

  Crashed: com.apple.NSURLSession-delegate
  0  libobjc.A.dylib                0x4174 objc_release + 16
  1  libobjc.A.dylib                0x4174 objc_release_x0 + 16
  2  libobjc.A.dylib                0x21d4 AutoreleasePoolPage::releaseUntil(objc_object**) + 196
  3  libobjc.A.dylib                0x5bdc objc_autoreleasePoolPop + 256
  4  libdispatch.dylib              0xb548 _dispatch_lane_serial_drain + 688
  5  libdispatch.dylib              0xc0d8 _dispatch_lane_invoke + 436
  6  libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
  7  libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
  8  libsystem_pthread.dylib        0xb7c start_wqthread + 8
  

초기 구동시, naver ad 를 3개 요청하는데요.

            case .MainTop:
                return "Tmap_AdUnit_top_ios-N774476171"
            case .MainBanner:
                return "Tmap_AdUnit_main_ios-N774476171"
            case .NaviTop:
                return "Tmap_AdUnit_navi_ios-N774476171"

내부적으로 image나 기타 object 에서 release 가 중복으로 이뤄지는 경우가 없는지 확인 요청 드립니다. 
확인 부탁드립니다. 

아래는 crash 발생시 콜스택 공유 드립니다. 
감사합니다. 

#. Crash 콜 스택 

com.apple.main-thread
0  libicucore.A.dylib             0x17baf0 icu::number::LocalizedNumberFormatter::LocalizedNumberFormatter(icu::number::impl::MacroProps&&, icu::Locale const&) + 228
1  libicucore.A.dylib             0x122d54 icu::DecimalFormat::touch(UErrorCode&) + 240
2  libicucore.A.dylib             0x126f6c icu::DecimalFormat::setNegativePrefix(icu::UnicodeString const&) + 160
3  libicucore.A.dylib             0x1eea24 icu::SimpleDateFormat::parseInt(icu::UnicodeString const&, icu::Formattable&, int, icu::ParsePosition&, signed char, icu::NumberFormat const*) const + 352
4  libicucore.A.dylib             0x1ebc5c icu::SimpleDateFormat::subParse(icu::UnicodeString const&, int&, char16_t, int, signed char, signed char, signed char*, int&, icu::Calendar&, int, icu::MessageFormat*, UTimeZoneFormatTimeType*, int*) const + 1252
5  libicucore.A.dylib             0x1eae2c icu::SimpleDateFormat::parse(icu::UnicodeString const&, icu::Calendar&, icu::ParsePosition&) const + 1060
6  libicucore.A.dylib             0x21de6c udat_parseCalendar + 228
7  CoreFoundation                 0xde768 CFDateFormatterGetAbsoluteTimeFromString + 552
8  CoreFoundation                 0x499a8 CFDateFormatterCreateDateFromString + 128
9  Foundation                     0x46ba8 getObjectValue + 248
10 Foundation                     0x55938 -[NSDateFormatter getObjectValue:forString:errorDescription:] + 196
11 Foundation                     0x55838 -[NSDateFormatter dateFromString:] + 56
12 T map                          0x6003c +[NSDate(Tmap) dateWithString:format:] + 39 (NSDate+Tmap.m:39)
13 T map                          0xb1ccb8 RecentMainData.lastServiceDate.getter + 89 (MainDataManager.swift:89)
14 T map                          0xb3a5f8 closure #1 in MainDataManager.sortRecentData(sourceArray:sortType:) + 4319733240
15 T map                          0xb4ce50 specialized closure #1 in UnsafeMutableBufferPointer._stableSortImpl(by:) + 4319809104 (<compiler-generated>:4319809104)
16 T map                          0xb498bc specialized UnsafeMutableBufferPointer._stableSortImpl(by:) + 4319795388 (<compiler-generated>:4319795388)
17 T map                          0xb1083c specialized MutableCollection<>.sort(by:) + 4319561788 (<compiler-generated>:4319561788)
18 T map                          0xb388d8 MainDataManager.sortRecentData(sourceArray:sortType:) + 897 (MainDataManager.swift:897)
19 T map                          0xb2ed8c MainDataManager.makeRecentMainData(withMyFavorite:) + 783 (MainDataManager.swift:783)
20 T map                          0xb2d954 MainDataManager.reloadRecentMainData() + 728 (MainDataManager.swift:728)
21 T map                          0xb1db9c MainDataManager.().init() + 213 (MainDataManager.swift:213)
22 T map                          0xb1e3ec @objc MainDataManager.().init() + 4319618028 (<compiler-generated>:4319618028)
23 T map                          0xa55f3c specialized AccountAuthManager.loadUserData() + 260 (MainDataManager.swift:260)
24 T map                          0xa49834 AccountAuthManager.handleAuthCompleted() + 158 (AccountAuthManager.swift:158)
25 T map                          0xa4e6f4 AccountAuthManager.handleAuthTmapResponse(_:) + 672 (AccountAuthManager.swift:672)
26 T map                          0xa49250 closure #1 in AccountAuthManager.doTask(completion:) + 4318745168
27 T map                          0xa49498 closure #2 in AccountAuthManager.doTask(completion:) + 4318745752
28 Combine                        0xaf44 Subscribers.Sink.receive(_:) + 96
29 Combine                        0xaa60 protocol witness for Subscriber.receive(_:) in conformance Subscribers.Sink<A, B> + 24
30 Combine                        0x11f20 closure #1 in Publishers.ReceiveOn.Inner.receive(_:) + 276
31 libswiftDispatch.dylib         0xfd4 thunk for @escaping @callee_guaranteed () -> () + 36
32 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
33 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
34 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
35 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
36 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
37 CoreFoundation                 0x7a560 __CFRunLoopRun + 1992
38 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
39 GraphicsServices               0x135c GSEventRunModal + 164
40 UIKitCore                      0x39cf58 -[UIApplication _run] + 888
41 UIKitCore                      0x39cbbc UIApplicationMain + 340
42 T map                          0xce6b0 main + 11 (main.swift:11)
43 ???                            0x1b7430dec (Missing)

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

NSOperationQueue 0x155d69100 (QOS: UNSPECIFIED)
0  libsystem_malloc.dylib         0x3768 malloc_zone_free + 120
1  libswiftCore.dylib             0x3be43c bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 132
2  Foundation                     0x235f4c NSData.subscript.getter + 316
3  NaverAdsServices               0x12ea0 block_destroy_helper + 10040
4  NaverAdsServices               0x12928 block_destroy_helper + 8640
5  NaverAdsServices               0x14244 block_destroy_helper + 15068
6  NaverAdsServices               0x12d6c block_destroy_helper + 9732
7  NaverAdsServices               0x12bc8 block_destroy_helper + 9312
8  NaverAdsServices               0x132c8 block_destroy_helper + 11104
9  NaverAdsServices               0x108c0 block_destroy_helper + 344
10 NaverAdsServices               0x10a04 block_destroy_helper + 668
11 T map                          0x100ce58 -[GFPNDANativeSimpleAd image] + 4324789848
12 T map                          0x1006410 -[GFPNDANativeAdaptor image] + 4324762640
13 T map                          0xfdf4b0 -[GFPMediationSimpleNativeAd initWithNativeAdAdaptor:responseInfo:] + 4324603056
14 T map                          0xfe5680 __98-[GFPUnifiedMediator loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:]_block_invoke + 4324628096
15 T map                          0xfcb4b8 -[GFPMediationUnifiedStrategy completeWithAdAdaptor:error:responseInfo:] + 4324521144
16 T map                          0xfdbe4c __90-[GFPMediationProcessor findAdWithAdUnitID:adParam:videoParam:extraParam:timeoutInterval:]_block_invoke.9 + 4324589132
17 Foundation                     0xa6ef4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
18 Foundation                     0x7b000 -[NSBlockOperation main] + 104
19 Foundation                     0x7af90 __NSOPERATION_IS_INVOKING_MAIN__ + 16
20 Foundation                     0x3c4b8 -[NSOperation start] + 708
21 Foundation                     0x3c1ec __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
22 Foundation                     0x4187c __NSOQSchedule_f + 172
23 libdispatch.dylib              0x12fc4 _dispatch_block_async_invoke2 + 148
24 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
25 libdispatch.dylib              0x7330 _dispatch_continuation_pop + 504
26 libdispatch.dylib              0x6998 _dispatch_async_redirect_invoke + 584
27 libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
28 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
29 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
30 libsystem_pthread.dylib        0xb7c start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Foundation                     0x41fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41e9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4cfcc8 -[UIEventFetcher threadMain] + 416
10 Foundation                     0x5b524 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

NSOperationQueue 0x155d07030 (QOS: UNSPECIFIED)
0  libsystem_malloc.dylib         0x16d2c _nanov2_free + 576
1  libswiftCore.dylib             0x3bd618 _swift_release_dealloc + 56
2  libswiftCore.dylib             0x3be43c bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 132
3  Foundation                     0x235f4c NSData.subscript.getter + 316
4  NaverAdsServices               0x12ea0 block_destroy_helper + 10040
5  NaverAdsServices               0x12928 block_destroy_helper + 8640
6  NaverAdsServices               0x14244 block_destroy_helper + 15068
7  NaverAdsServices               0x12d6c block_destroy_helper + 9732
8  NaverAdsServices               0x12bc8 block_destroy_helper + 9312
9  NaverAdsServices               0x132c8 block_destroy_helper + 11104
10 NaverAdsServices               0x108c0 block_destroy_helper + 344
11 NaverAdsServices               0x10a04 block_destroy_helper + 668
12 T map                          0x100ce58 -[GFPNDANativeSimpleAd image] + 4324789848
13 T map                          0x1006410 -[GFPNDANativeAdaptor image] + 4324762640
14 T map                          0xfdf4b0 -[GFPMediationSimpleNativeAd initWithNativeAdAdaptor:responseInfo:] + 4324603056
15 T map                          0xfe5680 __98-[GFPUnifiedMediator loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:]_block_invoke + 4324628096
16 T map                          0xfcb4b8 -[GFPMediationUnifiedStrategy completeWithAdAdaptor:error:responseInfo:] + 4324521144
17 T map                          0xfdbe4c __90-[GFPMediationProcessor findAdWithAdUnitID:adParam:videoParam:extraParam:timeoutInterval:]_block_invoke.9 + 4324589132
18 Foundation                     0xa6ef4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
19 Foundation                     0x7b000 -[NSBlockOperation main] + 104
20 Foundation                     0x7af90 __NSOPERATION_IS_INVOKING_MAIN__ + 16
21 Foundation                     0x3c4b8 -[NSOperation start] + 708
22 Foundation                     0x3c1ec __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
23 Foundation                     0x4187c __NSOQSchedule_f + 172
24 libdispatch.dylib              0x12fc4 _dispatch_block_async_invoke2 + 148
25 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
26 libdispatch.dylib              0x7330 _dispatch_continuation_pop + 504
27 libdispatch.dylib              0x6998 _dispatch_async_redirect_invoke + 584
28 libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
29 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
30 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
31 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x20aa0 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x20e80 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x17f94 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x1a7f0 FIRCLSMachExceptionServer + 521 (FIRCLSMachException.c:521)
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

Crashed: com.apple.NSURLSession-delegate
0  libobjc.A.dylib                0x4174 objc_release + 16
1  libobjc.A.dylib                0x4174 objc_release_x0 + 16
2  libobjc.A.dylib                0x21d4 AutoreleasePoolPage::releaseUntil(objc_object**) + 196
3  libobjc.A.dylib                0x5bdc objc_autoreleasePoolPop + 256
4  libdispatch.dylib              0xb548 _dispatch_lane_serial_drain + 688
5  libdispatch.dylib              0xc0d8 _dispatch_lane_invoke + 436
6  libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
7  libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
8  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  JavaScriptCore                 0x113d84 scavenger_thread_main + 1620
3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
4  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x14d4264 vsm::SerialExecutionQueue::executor() + 597484
4  T map                          0x14d45f0 void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::SerialExecutionQueue::*)(), vsm::SerialExecutionQueue*>>(void*) + 598392
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2586f0 _CFURLStorageSessionDisableCache + 60900
8  Foundation                     0x5b524 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x143e0d0 vsm::DelayedMessageQueue::next() + 296144
4  T map                          0x15425f4 vsm::TrafficDownloader::downloadTrafficThread() + 1048956
5  T map                          0x1544c60 void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::TrafficDownloader::*)(), vsm::TrafficDownloader*>>(void*) + 1058792
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x143e0d0 vsm::DelayedMessageQueue::next() + 296144
4  T map                          0x1615424 vsm::TileStreamingManager::TileDownloadingThread() + 1912748
5  T map                          0x16196d4 void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::TileStreamingManager::*)(), vsm::TileStreamingManager*>>(void*) + 1929820
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x143e0d0 vsm::DelayedMessageQueue::next() + 296144
4  T map                          0x156deac vsm::AsyncTaskQueue::mainTaskExecutor() + 1227316
5  T map                          0x156ef10 void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::AsyncTaskQueue::*)(), vsm::AsyncTaskQueue*>>(void*) + 1231512
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x156e1c4 vsm::BlockingQueue<std::__1::function<void ()>>::pop(std::__1::function<void ()>&) + 1228108
4  T map                          0x156df30 vsm::AsyncTaskQueue::taskExecutor(int) + 1227448
5  T map                          0x156f0bc void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::AsyncTaskQueue::*)(int), vsm::AsyncTaskQueue*, int>>(void*) + 1231940
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x156e1c4 vsm::BlockingQueue<std::__1::function<void ()>>::pop(std::__1::function<void ()>&) + 1228108
4  T map                          0x156df30 vsm::AsyncTaskQueue::taskExecutor(int) + 1227448
5  T map                          0x156f0bc void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::AsyncTaskQueue::*)(int), vsm::AsyncTaskQueue*, int>>(void*) + 1231940
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12ef8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  T map                          0x153ba88 vsm::BlockingQueue<std::__1::shared_ptr<vsm::TextObject>>::pop(std::__1::shared_ptr<vsm::TextObject>&) + 1021456
4  T map                          0x153ae84 vsm::TextRenderer::textRenderThread() + 1018380
5  T map                          0x153c3fc void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (vsm::TextRenderer::*)(), vsm::TextRenderer*>>(void*) + 1023876
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요.
정확한 이슈 파악을 위해 초기 광고 로드 부분의 소스 확인이 가능할까요?

**Comment by leejj121** [comment]
초기 구동시, 동일 viewController로 3개의 광고 요청을 보냅니다. 
관련 소스도 첨부 합니다. 

NaverADManager.shared().requestSimpleAD(type:.MainTop, rootViewController: self)
NaverADManager.shared().requestSimpleAD(type:.MainBanner, rootViewController: self)
NaverADManager.shared().requestSimpleAD(type:.NaviTop, rootViewController: self)


[NaverADManager.swift.zip](https://github.com/naver/nam-sdk-ios/files/12654111/NaverADManager.swift.zip)

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요
NaverAdManager.shared() 에서 멤버 변수로 GFPAdLoader를 재활용하는 것으로 보이는데요,
GFPAdLoader는 일회용 사용이 원칙입니다. RequestAd시마다 로더를 재생성해서 사용하시면 문제가 없을 듯 합니다.

**Comment by shhan-sys** [comment]
@leejj121 님, 안녕하세요.
구현부나 로직 자체에 이상이 있는 것 같지는 않습니다.
따로 object나 image를 release를 NAMSDK내부에서 하고 있지는 않습니다.

의심되는 부분은 현재 NativeAdInstance의 GFPAdLoader가 재활용해서 사용하고 계신 것 같은데
초기 구동시 광고 요청 후, 재요청할 때 문제가 발생할 것 같습니다.
( GFPAdLoader를 광고 요청당 1번만 사용하는 일회용 사용이 원칙입니다. )

**Comment by leejj121** [comment]
네. 답변 감사합니다 
광고 요청 관련해서 동일한 로직으로 이전 버전 4.5.4에서는 나오지 않는 사항이어서 확인 요청드렸었는데요.

가이드 주신 내용으로 변경하여 진행해 보겠습니다. 
감사합니다.
