### ISSUE TITLE
Xcode 14.2에서 NAM-SDK-iOS v6.8.2 컴파일 시 발생하는 에러 관련 문의

### ISSUE THREAD

**Issue by nacker-work** [naver/nam-sdk-ios#22]
안녕하세요.

NAM-SDK-iOS 버전 v6.8.2로 업데이트한 후 Xcode 14.2에서 컴파일할 때
"Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56" 에러 발생하고 있습니다.
하지만 Xcode 14.3에서는 해당 에러 발생하지 않습니다.
혹시 v6.8.2 버전 이상을 적용하기 위해서는 Xcode 14.3 이상이 필수인지 문의드립니다.

감사합니다.

**Comment by shhan-sys** [comment]
안녕하세요, @nacker-work 님
현재 최신 버전에서는 15+ 버전 사용을 권장하고 있습니다.

**Comment by nacker-work** [comment]
답변 주셔서 감사드립니다.
혹시 Xcode 14.2 버전에서 컴파일 에러나는 현상 수정된 버전 배포 계획 있으신지 문의드립니다.

**Comment by shhan-sys** [comment]
안녕하세요, @nacker-work 님
현재 기능상 Xcode 15+ 가 필요한 상황으로 구버전 지원은 고려하지 않고 있습니다.
