### ISSUE TITLE
XCode16을 통한 AppStore 업로드 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by Karl-Styner** [naver/nam-sdk-ios#23]
오류 내용은 아래와 같습니다.
Invalid Executable. The executable  '.../OMSDK_NaverCorp.framework/OMSDK_NaverCorp' contains bitcode. 

bitcode가 포함된 것을 제거해야 하는 것으로 보입니다. 빠른 수정이 필요해 월요일에 영업사를 통해 따로 문의도 드릴 예정입니다만, 이쪽으로도 공유드립니다.

**Comment by sodam-k** [comment]
@Karl-Styner 님 안녕하세요. 해당 이슈 이미 인지하고 있으며 대응중입니다.
IAB 측에서 제공하는 OMSDK 라이브러리를 업데이트 하여 7.9.4로 금일 배포 예정이니, 참고 부탁드립니다. 감사합니다.

**Comment by sodam-k** [comment]
@Karl-Styner 님 7.9.4 버전 배포되어 공유드립니다. 감사합니다.
: https://github.com/naver/nam-sdk-ios/releases/tag/7.9.4

**Comment by Karl-Styner** [comment]
7.9.4를 받아 테스트해보았으나 여전히 같은 에러가 발생합니다.
당장 급한 관계로...

bitcode를 스트립하는 코드를 Podfile 안에,
`xcrun --sdk iphoneos bitcode_strip -r Pods/NAMSDK/NAMSDK/xcframework/libraries/OMSDK_Navercorp.xcframework/ios-arm64/OMSDK_Navercorp.framework/OMSDK_Navercorp -o Pods/NAMSDK/NAMSDK/xcframework/libraries/OMSDK_Navercorp.xcframework/ios-arm64/OMSDK_Navercorp.framework/OMSDK_Navercorp` 

와 같이 넣어 처리하여 배포되는 것을 확인하였으나, 이렇게 하는 것이 정상적인 상황은 아닌 것 같습니다.

**Comment by sodam-k** [comment]
@Karl-Styner 님 안녕하세요. IAB 쪽에서 1.5.1 사용시 이슈가 없다고 답변을 받아 업데이트를 진행하였는데요.
bitcode가 제거가 잘 되지 않은 것으로 보여, IAB측에 재문의 드려보겠습니다.

**Comment by sodam-k** [comment]
@Karl-Styner 님 안녕하세요. IAB 쪽 답변이 지연되고 있음을 공유드립니다.
위 이슈의 단기 대응으로 nam 측에서 omsdk의 bitcode를 제거하였고, 해당 버전이 7.10.0 으로 배포되었음을 공유드립니다. 감사합니다.
