### ISSUE TITLE
광고 Size 관련 Delegate 호출 문의

### ISSUE THREAD

**Issue by hm138** [naver/nam-sdk-ios#7]
안녕하세요. @shhan-sys 님.
네이버 광고의 Size 에 따라 상위 뷰의 높이를 결정하는 기능 적용중입니다.
해당 기능 적용을 위해 광고 로드 성공시 하기 광고 Size 관련 Delegate 호출 보장되는지 문의드립니다.

[배너]
```
GFPBannerViewDelegate
- (void)bannerView:(GFPBannerView *)bannerView didChangeWith:(GFPBannerAdSize *)size;
```

[네이티브 심플]
```
GFPNativeSimpleAdDelegate
- (void)nativeSimpleAd:(GFPNativeSimpleAd *)nativeSimpleAd didChangeMediaViewSizeWith:(CGSize)size;
```

**Comment by shhan-sys** [comment]
@hm138 님, 안녕하세요.
해당 델리게이트들은 항상 호출되지는 않고, 사이즈 변경이 있는 경우에만 호출됩니다.
[배너]
- GFPAdLoader의 delegate에서 인자로 넘겨받은  GFPBannerView에 사이즈를 맞춰 배열
- 이후 변경 사항이 있다면 해당 델리게이트 함수 노출, 변동이 없다면 didChangeWith는 불리지 않습니다.
[네이티브 심플]
- GFPNativeSimpleAdView의 크기와 광고의 할당 사이즈가 다르다면 didChangeMediaViewSizeWith delegate가 호출되며, 광고 응답값에 맞게 이미 영역이 딱 맞아 떨어진다면 불리지는 않습니다.

**Comment by hm138** [comment]
안녕하세요. @shhan-sys 님.
답변 감사드립니다.

추가 적으로 하기 내용 문의드립니다.
1. SDK내 사이즈 변경 체크 로직 실행 시점들
2. 광고 최초 로드시 배너/네이티브심플 해당 Delegate 호출 안되는 경우가 있는지 여부

**Comment by hm138** [comment]
안녕하세요. @shhan-sys 님.
답변 감사드립니다.

1. 상위뷰(배너 및 네이티브심플 뷰의 superview)의 높이를 네이버 광고 높이와 동일하게 적용하는 기능 구현중입니다. 혹시 광고 로드 성공후 해당 광고 Size 를 알 수 있는 방법이 있다면 공유 부탁드립니다.

2. 현재 배너/네이티브 심플 둘다 광고 **최초** 로드 성공시, 해당 델리게이트들 호출되고 있는것 같습니다.
**최초** 로드 성공후에도 해당 델리게이트들 호출되지 않는 케이스에 대한 예시가 있다면 공유 부탁드리겠습니다.

**Comment by shhan-sys** [comment]
@hm138 님, 답변 드리겠습니다~

 기본적으로 해당 델리게이트들은 직접적으로 내부 뷰를 조정해주는 것이 아닌 서비스에서 사이즈 조절이 필요할 경우에 호출되는 메서드들입니다. 고로, 해당 델리게이트 호출 시에는 전달받는 사이즈로 상위 뷰와 서비스에서 접근 가능한 레벨의 광고 뷰를 모두 조정해주시면 됩니다.
(배너인 경우에는 GFPBannerView, 네이티브 심플인 경우에는 GFPNativeSimpleAdView)

 네이티브 심플인 경우에는 기본 사이즈를 안내받으실 텐데, 해당 사이즈로 먼저 뷰를 지면에 배치한 이후에 로드하는 방식을 사용하신다면 먼저 배치된 사이즈와 광고 사이즈가 동일한 경우에는 해당 델리게이트가 호출되지 않으나, 그렇지 않은 경우에는 호출되는 메서드의 인자로 조정해주시면 됩니다.

1. 상위뷰(배너 및 네이티브심플 뷰의 superview)의 높이를 네이버 광고 높이와 동일하게 적용하는 기능 구현중입니다. 혹시 광고 로드 성공후 해당 광고 Size 를 알 수 있는 방법이 있다면 공유 부탁드립니다.

[배너] -> GFPAdLoader를 사용 시 인자로 받은 GFPBannerView의 frame.size와 동일하게 맞춰주시면 됩니다. 이후에 해당 델리게이트가 호출된다면, 인자로 받은 size로 직접 조정해주시면 됩니다.
[네이티브 심플] -> 심플은 기존의 배치된 뷰를 해당 델리게이트 호출 시에만 조정해주시면 됩니다.

2. 현재 배너/네이티브 심플 둘다 광고 최초 로드 성공시, 해당 델리게이트들 호출되고 있는것 같습니다.
최초 로드 성공후에도 해당 델리게이트들 호출되지 않는 케이스에 대한 예시가 있다면 공유 부탁드리겠습니다.

[배너] -> 현재 배너는 adm에 resize를 반드시 호출하게 되어 있습니다. 
[네이티브 심플] -> 네이티브 응답값에 따라 광고 로드 전 뷰 사이즈를 375/80 으로 배치하고 호출하면 해당 델리게이트 함수가 호출되지 않을 것 같습니다.

**Comment by hm138** [comment]
@shhan-sys 님.
답변 감사드립니다.

말씀주신대로 **네이티브 심플 광고** GFPNativeBaseView.nativeAd 값 적용전 GFPNativeBaseView.mediaView 사이즈 375/80 로 적용시 해당 델리게이트 함수가 호출되지 않는것 확인하였으며 GFPNativeBaseView.mediaView 사이즈별로 아래와 같이 동작하는것 확인 하였습니다.
- W375 이상, H80: 호출 안됨
- W375 이상, H80 이 아닐 경우: Width 는 mediaView.Width, Height 는 80 으로 호출 됨
- W375 미만: Width 는  mediaView.Width, Height 는 80*(mediaView.Width/375)

네이티브 심플 광고 기본 사이즈(80) 값이 추후 운영단계에서 어드민 혹은 Console 설정으로 80 유지 보장받을수 있는지 문의드립니다. (보장 받지 못할 경우 사용자에게 짧은 시간에 광고뷰의 사이즈가 달라지는 경험을 줄 것 같아 지양하고 싶은 마음입니다.)
- 보장 받을 수 있을 경우: 상기 답변 주신 방식으로 적용
- 보장 받을 수 없는 경우: GFPNativeBaseView.mediaView 높이를 작은값(e.g. 10)으로 적용(해당 델리게이트 호출 보장), 델리게이트 호출 받은후 사용자에게 광고뷰 표시

**Comment by shhan-sys** [comment]
@hm138 님, 확인 감사합니다.
 광고 설정 시 어드민에서 광고 사이즈 등록을 하면 해당 사이즈가 보장됩니다. 다만, 해당 부분은 적용 시 기획 단계에서 이야기가 좀 더 필요한 부분 일 듯 싶습니다.

**Comment by hm138** [comment]
@shhan-sys 님.
답변 감사드립니다.

아래 내용 추가 문의드립니다.
1. 어드민 관리(광고 사이즈 등록) 주체, e.g. SK플래닛, 네이버, 광고주, ...
2. iOS 의 경우 어드민에 375x80 사이즈로 등록되어 있어서 W375, H80 기준으로 동작이 상이한 것인지 문의드립니다. (만약 맞을 경우, 320x100 으로 등록시 W320, H100 기준으로 동작 하는지 추가 문의드립니다.)

**Comment by shhan-sys** [comment]
@hm138 님
1. 어드민 관리(광고 사이즈 등록) 주체, e.g. SK플래닛, 네이버, 광고주, ...
-> 저희쪽에 확인한 바로는 SK플래닛 쪽에서 직접 권한을 얻어 셋팅하도록 이야기된 부분이라고 합니다.

2. iOS 의 경우 어드민에 375x80 사이즈로 등록되어 있어서 W375, H80 기준으로 동작이 상이한 것인지 문의드립니다. (만약 맞을 경우, 320x100 으로 등록시 W320, H100 기준으로 동작 하는지 추가 문의드립니다.)
->  현재 375x80 기준으로 등록되어있다면 위처럼 작동하는 게 항상 보장됩니다. 320x100 으로 등록하면 해당 사이즈대로 동작이 보장됩니다. 다만, 두 가지 사이즈를 동시 등록해서 혼용해서 사용하실 수 있으므로 이 때는 광고호출 시 내려오는 사이즈마다 메서드를 통해 조정해주셔야 합니다.

**Comment by hm138** [comment]
@shhan-sys 님.
답변 감사드립니다.

어드민 관리 관련 저희 담당 매니저님께 확인해보니 상용 admin만 허용된 상태이며, 테스트 환경 셋팅은 네이버에서 설정하고 있다고 말씀주셨습니다. 현재 테스트 admin 에 어떤값으로 설정되어 있는지 문의드립니다. (가능하다면 Android 설정값도 공유 부탁드립니다.)

**Comment by shhan-sys** [comment]
@hm138 님, 어드민에서 확인한 값 알려드립니다.
배너 : 360 x 185
네이티브 : 1200x628, 640x148, 100x100, 720x330, 720x270, 360x165, 750x160, 375x80, 320x160, 630x80, 320x50, 240x240, 728x90, 360x185 

iOS, AOS 모두 동일합니다. 다만, 해당 사이즈에 맞는 소재가 세팅되지 않았다면 사이즈는 내려오지 않습니다.

**Comment by hm138** [comment]
@shhan-sys 님.
답변 감사드립니다.

해당 사이즈에 맞는 소재가 세팅된 것중 W375 가 아닌 광고가 있다면 unitID 공유 부탁 드립니다.

**Comment by hm138** [comment]
@shhan-sys 님.

말씀주신대로 SKP 담당 매니저님께 요청 후 테스트 진행하겠습니다.
감사합니다.

**Comment by NAM-Ad** [comment]
@hm138 님, 안녕하세요. 
네이버 기획에서 회신드립니다. 

현재 저희 쪽 어드민에 세팅된 내용을 보면, 아래와 같이 소재 사이즈가 응답되도록 설정된 상태입니다.
아래 사이즈 외 소재는 광고 응답 범위에서 제외된다고 보시면 됩니다.
- 배너 : `360x185`
- 네이티브 : `375x80`

> 상기 설정은 테스트/상용 어드민 모두 동일하며, 네이티브 심플 광고가 나가는 지면 대상으로는 W375가 아닌 unitId가 적용되지 않을 예정입니다. 

혹시 추가로 확인 필요하신 사항 있으시면 말씀 부탁드립니다.

**Comment by hm138** [comment]
@NAM-Ad 님. 안녕하세요.

말씀주신 내용이 네이티브 심플 광고의 경우 W375 가 아닌경우 광고 생생이 불가능하거나 정상동작하지 않는다는 의미인지 문의드립니다.

**Comment by NAM-Ad** [comment]
@hm138 , 

네 안녕하세요. 

SKP 기준, 네이티브 심플 광고가 적용되는 adUnitId의 경우, **W375 외 물량에 대해서는 광고 요청을 하지 않도록 설정**돼 있습니다 (따라서, W375 물량에 대해서만 응답을 보장받습니다)
> 위와 같은 설정은 SKP 측과 해당 adUnitId가 적용되는 '지면 사이즈'에 대한 사전 협의가 있었기 때문인데요.
> 필요 시 W375 외 물량에 대해서 광고 요청-응답 받을 수 있도록 설정을 변경할 수 있는 구조이긴 합니다.

**Comment by hm138** [comment]
@NAM-Ad 님. 답변 감사드립니다.

제가 이해한 바로는 SKP 기준 배너 360x185, 네이티브  375x80 사이즈 물량에 대해서만 광고 요청을 하도록 협의했다는 것으로 이해했습니다.
아래 내용 문의드립니다.

1. 협의 내용에 Width 뿐만 아니라 Height 에 대해서도 포함 되는지 여부 (네이티브 375x100도 협의에 포함된 사이즈인지 말씀주시면 될 것 같습니다.)
2. 어드민에서 네이티브 375x80 등록후 앱에서 광고뷰의 사이즈를 414x80 으로 잡아도 동작하는지 여부(현재 동작하고 있습니다. 추후에도 동작 보장되는지 말씀주시면 될 것 같습니다.)
3. 어드민에서 네이티브 320x80 으로 등록할 경우 처리 방식(e.g. 등록 불가, 광고 로드 실패, ...)

**Comment by hm138** [comment]
@NAM-Ad 님. 답변 감사드립니다.

각 번호별 아래 내용 문의드립니다.
1. 어드민 등록 기준 A, B, 다른방식 중 어떤 방식으로 협의 되었는지 문의드립니다.
  A. W 고정/H 가변 으로 협의
  B. W/H 둘다 고정으로 협의
3. 만약 어드민에서 협의되지 않은 사이즈(e.g. 320x80) 으로 등록할 경우 어떻게 동작하게 되는지 문의드립니다.

**Comment by NAM-Ad** [comment]
@hm138 님, 문의주신 내용 회신드립니다. 

**1. 어드민 등록 기준 A, B, 다른방식 중 어떤 방식으로 협의 되었는지 문의드립니다.**
> 기본적으로 `사이즈 고정/가변 여부`에 대한 설정은 저희 쪽 어드민에서 적용하지 않고, 매체 쪽 개발에서 SDK 가이드를 참조하여 적용하는 것으로 이해하고 있습니다 (참고 : https://github.com/naver/nam-sdk-ios/blob/main/docs/banner/guide.md#%ED%99%95%EC%9E%A5%ED%98%95-%EB%A0%88%EC%9D%B4%EC%95%84%EC%9B%83-%EC%84%A4%EC%A0%95-fluid)
> 어드민 화면 기준으로는, 배너/네이티브 모두 고정된 사이즈를 선택하도록 되어있습니다. 

**2. 만약 어드민에서 협의되지 않은 사이즈(e.g. 320x80) 으로 등록할 경우 어떻게 동작하게 되는지 문의드립니다.**
> 이론적으로는 어드민에 협의되지 않은 사이즈 (e.g. 320x80) 를 등록할 경우, DSP로부터 해당 사이즈에 대한 응답을 받을 수 있는 구조입니다 (DSP가 320x80에 대한 물량을 보유하고 있다는 가정하)

> 다만, 이는 구조상 그런 것이고, **실제로는 매체 측과 협의되지 않은 사이즈로 광고가 요청될 일은 발생하지 않습니다**.
> 저희 운영 정책상 매체와 협의되지 않은 사이즈는 어드민에서 선택 불가하도록 제어하고 있습니다.
> (참고) 아래는 SKP 계정 예시입니다. 360x185 사이즈로 세팅된 광고유닛으로 수익화 설정을 할 경우, 360x185 외 사이즈는 조회가 불가하도록 설정돼 있습니다.    
>> ![image](https://user-images.githubusercontent.com/109189952/178858582-e3e192ae-d74c-4c2d-a9f4-10fd14777906.png)

**Comment by hm138** [comment]
@NAM-Ad 님. 답변 감사드립니다.

**어드민에서 Banner(360x180), Native Simple(375x80) 이외에는 등록 불가능한걸로 이해하였습니다.**

어드민에서 다른 사이즈 등록이 불가하므로 꼭 필요한 것은 아니지만
테스트 및 선행적 예외처리 체크를 위해 협의된 사이즈가 아닌 다른 사이즈로 등록된 케이스에 대한 테스트 환경 조성이 가능한지 문의드립니다.

**Comment by NAM-Ad** [comment]
@hm138 님, 

어드민에 **사전 협의되지 않은 사이즈가 등록된 경우**에 대한 환경 세팅이 가능할지 문의주셨는데요. 

저희 어드민에 사전 협의된 사이즈 - `Banner(360x180), Native Simple(375x80)` - 외의 상품 및 사이즈를 등록하더라도,
해당 물량에 대한 DSP 측 응답을 보장 받을 수 없는 상황이라 말씀하신 방식의 테스트 진행은 어려울 것으로 보입니다.
> DSP 측으로부터 전달받는 응답 정보가 없을 경우, 렌더링 시 참고하는 소재 정보 또한 없을 것이므로 예외처리에 대한 검증 불가 

혹시 추가로 검증 필요한 방식이 있다면 말씀 부탁드립니다. 감사합니다.

**Comment by hm138** [comment]
넵. 확인하였습니다.
@shhan-sys , @NAM-Ad 님 지원해주셔서 감사합니다.
