### ISSUE TITLE
네이티브 심플 광고 UI 정합 문의

### ISSUE THREAD

**Issue by hm138** [naver/nam-sdk-ios#8]
[환경]
- SDK 버전: v0.0.5
- Device: iPhone 13 Pro Max
- GFPNativeSimpleAdDelegate didChangeMediaViewSizeWith 호출된 사이즈: (428.0, 80.0)

상기 환경에서 첫번째 광고부터 Height 80(x1), 160(x2), 240(x3) 적용한 스크린 캡쳐 이미지 첨부 해드립니다.
<img width="150" alt="20220530_1358" src="https://user-images.githubusercontent.com/96452452/178430599-cfbc6b18-0b6d-40e2-8846-aea8e689ca95.png">

첫번째 Height 80(x1) 광고의 UI 가 조금 부자연스러운 느낌이 있는 것 같습니다.
확인 부탁드립니다.

**Comment by sodam-k** [comment]
@hm138 님 안녕하세요. 문의 주신 이슈 내용 살펴보았습니다.
Height 가 80일 때 광고 UI 가 부자연스럽다고 느끼신 부분이, 혹시 AD|X 마크의 위치 때문일까요?

네이티브 심플 광고의 경우, 광고 이미지 우상단에 AD 마크를 붙이고 있으므로 참고 부탁드립니다. 
  - AD 마크에 대한 스펙이며 안드로이드도 동일합니다.
  - <img width="300" alt="스크린샷 2022-07-12 오후 4 48 48" src="https://user-images.githubusercontent.com/74757810/178439081-4be8c7ae-018c-4508-ab64-4c9706af6a09.png">

**Comment by hm138** [comment]
@sodam-k 님 안녕하세요.

개인적인 느낌으로 160(x2), 240(x3) 의 경우와 달리 80(x1) 인 경우, AD|X 마크 및 전체적인 콘텐츠들이 중앙에 몰린 느낌이라 문의 드립니다.
같은 조건에서 iPhone 12 mini(디바이스 Width 375) 의 경우 아래와 같이 전체적으로 자연스러운 느낌으로 표시되고 있는것 같습니다.
<img width="150" alt="20220712_1708" src="https://user-images.githubusercontent.com/96452452/178442546-f5f79f53-8432-4964-bec6-efc4d7020828.png">

**Comment by sodam-k** [comment]
안녕하세요 @hm138  님.
네이티브 심플의 경우 단말기에 따라 노출되는 이미지의 크기가 상이합니다. 이미지의 원본과 디바이스의 width 사이즈를 토대로 너비/높이를 계산하여 그리고 있습니다. 
정확하게는 simpleAdView의 width를 토대로 계산하나, simpleAdView의 width = 디바이스의 width 로 설정하도록 가이드를 드리고 있습니다.
(+ 산정되는 너비/높이값에 따라 이미지의 contentMode를 aspect fit, aspect fill 으로 설정하는 로직도 존재합니다.)

말씀주신 부분도 디바이스의 너비를 기준으로 이미지의 크기를 산정하기 때문에 나타나는 현상으로 보입니다.
다양한 해상도의 기기에서 최대한 어글리하지 않게 선택한 로직이며, 특정 기기(=프로맥스)에서 몰리는 느낌이 드는 부분은 감안 부탁드립니다.

**Comment by hm138** [comment]
@sodam-k 님.
답변 감사드립니다.

첨부해드린 스크린 캡쳐 이미지는 simpleAdView의 width = 디바이스의 width 로 설정해서 적용한 이미지입니다.
해당 케이스 특정 기기(=프로맥스)에서 몰리는 느낌이 드는 부분은 스펙 or 기타 여건상 의도된 기능으로 현행 유지로 이해해도 되는지 문의드립니다.

**Comment by sodam-k** [comment]
넵 해당 스펙은 os별로 모두 동일하게 적용되어 있으며, 현행대로 유지합니다 :)
