### ISSUE TITLE
배포 SDK 버전 문의

### ISSUE THREAD

**Issue by hm138** [naver/nam-sdk-ios#9]
최종 앱배포에 적용해야하는 NAM-SDK-iOS 버전 문의드립니다.
현재 v0.0.5 버전으로 QA 진행중입니다.

참고로 OK캐쉬백 App QA 및 배포 일정은 아래와 같으며 현재 QA 3차수 진행중입니다.
QA 일정
- 1차 : 7/4(월) ~ 7/7(목) (알파, 4일)
- 2차 : 7/8(금) ~ 7/13(수) (알파, 4일)
- 3차 : 7/14(목) ~ 7/19(화) (알파, 4일)
- 4차 : 7/20(수) ~ 7/26(화) (상용, 5일)
- R/T : 7/27 (수)
- 배포 목표일 : 7/28(목)

**Comment by shhan-sys** [comment]
@hm138 님, 안녕하세요
v4.3.0이 최종 버전이 될 예정입니다.
해당 버전은 이번 다음 주 월요일에 배포될 예정입니다.
